language: node_js
node_js:
  - '6'
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
  - npm run build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN,
  local_dir: 'dist'
  skip_cleanup: true
  on:
    branch: master
