language: node_js
node_js:
  - '6'
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
deploy:
  provider: pages
  local_dir: 'dist'
  skip_cleanup: true
  github_token: $GITHUB_PUBLIC_REPO_TOKEN
  on:
    branch: master
